name: Move to In Progress

on:
  pull_request:
    types: [opened, closed]

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Move to In Progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the project ID
          project_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${GITHUB_REPOSITORY}/projects | jq '.[] | select(.name == "Your Project Name") | .id')
          
          # Get the column ID of the "To Do" column
          column_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/projects/${project_id}/columns | jq '.[] | select(.name == "To Do") | .id')
          
          # Get the column ID of the "In Progress" column
          in_progress_column_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/projects/${project_id}/columns | jq '.[] | select(.name == "In Progress") | .id')
          
          # Get the list of cards in the "To Do" column
          cards=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/projects/columns/${column_id}/cards | jq -r '.[].id')
          
          # Move each card to the "In Progress" column
          for card_id in $cards; do
            curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" https://api.github.com/projects/columns/cards/${card_id}/moves -d "{\"position\":\"top\",\"column_id\":${in_progress_column_id}}"
          done

